name: Pull Request Quality Gate

on:
  pull_request:
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  quality:
    uses: ./.github/workflows/quality.yaml

  build:
    needs: quality
    uses: ./.github/workflows/image-build.yml
